- hosts: remoto
  gather_facts: False

  vars:
    var_do_playbook: 'Seu Nome'
    lista_do_playbook: ["Amarelo", "Vermelho", "Preto"]

  tasks:

    - name: Criando um template
      template:
        src: template.j2
        dest: /tmp/template_impacta.txt